### ISSUE TITLE
Update to zig 0.11

### ISSUE THREAD

**Issue by Shinyzenith** [waycrate/waylight#3]
This will deprecate the deps submodule and we can use build.zig.zon

**Comment by uncomfyhalomacro** [comment]
@Shinyzenith btw, you can't still use a rolling release distro for this since 0.11.0 requires glibc = 2.34. a point release should suffice e.g. opensuse leap 15.5 - https://build.opensuse.org/package/binaries/devel:tools:compiler/zig/15.5.

Another workaround is just using the precompiled one. such as river's `next-zig` branch.

**Comment by Shinyzenith** [comment]
I don't get what you mean exactly? I can't use zig 0.11 on a rolling release? @uncomfyhalomacro

**Comment by uncomfyhalomacro** [comment]
> I don't get what you mean exactly? I can't use zig 0.11 on a rolling release? @uncomfyhalomacro

Yes. Hence why archlinux does not have 0.11.0 for a week. The other workaround is just downloading the tarball containing the compiled binary. I cant compile it in tumbleweed hence the link i sent

**Comment by Shinyzenith** [comment]
@uncomfyhalomacro I'm on NixOS. I'm good.

**Comment by Shinyzenith** [comment]
@uncomfyhalomacro I'm on NixOS. I'm good.

**Comment by uncomfyhalomacro** [comment]
I use distrobox too. so I am good.
